version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-vt
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: virustotaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

volumes:
  postgres_data:
