apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: app-virustotal
type: Opaque
data:
  # PostgreSQL (db)
  POSTGRES_DB_MAIN: dmlydXN0b3RhbGRi
  POSTGRES_USER_MAIN: cG9zdGdyZXM=
  POSTGRES_PASSWORD_MAIN: cG9zdGdyZXM=

  # # PostgreSQL (db_mcp)
  MCP_POSTGRES_DB: Y3liZXJzZWM=
  MCP_POSTGRES_USER: cGd1c2Vy
  MCP_POSTGRES_PASSWORD: cGdwYXNz

  # # Backend
  OPENAI_KEY: -----REEMPLAZAR_POR_SU_PROPIA_API_KEY---------------
  VT_KEY: MWIzOWE2MWE3YTU4MWNlN2ZhZTFiMzEzNTVjOTk5MDQ2MTNlODA5ZTQ2ODJhMDNkMDU0N2M1NThlODUyYTg0NQ==
  DATABASE_URL_API: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLWRiOjU0MzIvdmlydXN0b3RhbGRi
  AUTH0_CLIENT_ID: aHR0cHM6Ly9zZWN1cmVzY2FuLmNvbS9hcGkvdjIv
  AUTH0_DOMAIN: ZGV2LW1rMDB3ZG1nejVubjZkMmMudXMuYXV0aDAuY29t

  # # MCP Client
  OPENAI_API_KEY: -----REEMPLAZAR_POR_SU_PROPIA_API_KEY---------------
  VT_API_KEY: NjViNGE1OTIzZjU0MjFlNjFlNGQzNTI3NTFmYjg0MDVmMzU4NjhlYmU3ZDIwM2NmMWFjODhkODEzNjQyN2E0YQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL3BndXNlcjpwZ3Bhc3NAZGJfbWNwOjU0MzIvY3liZXJzZWM=
  MCP_SERVER_CMD: cHl0aG9uIG1jcF9zZXJ2ZXIucHk=
  WHOIS_API_KEY: YXRfZVhkdWN0dE1icU1nZXYwOWY3VmJVVDRtOHpWWEk=

  # # MCP Client
  VITE_API_URL: aHR0cDovL2tvbmc6ODAwMC9hcGk=