apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: app-virustotal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: frontend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: app-virustotal
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
