apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: app-virustotal
data:
  kong.yml: |
    _format_version: "2.1"
    services:
      - name: api
        url: http://fastapi-vt:8000
        routes:
          - name: api-main-route
            paths:
              - /api
            strip_path: true
            methods: [GET, POST, PUT, DELETE, OPTIONS]
            protocols: [http, https]
      - name: mcp-api
        url: http://fastapi-mcp:8000
        routes:
          - name: mcp-api-route
            paths:
              - /mcp-api
            strip_path: true
            methods: [GET, POST, PUT, DELETE, OPTIONS]
            protocols: [http, https]
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET","POST","PUT","DELETE", "OPTIONS"]
          headers: ["Content-Type", "Authorization", "Accept"]  
          credentials: true