name: Container Security Scan

on:
  push:
    branches: [ main, imp-snyk ]
    paths:
      - 'Backend/Dockerfile'
      - 'Backend/requirements.txt'
      - 'docker-compose.yml'
      # - 'mcp-client/Dockerfile'
      # - 'mcp-client/requirements.txt'
      # - 'mcp-server/requirements.txt'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Cada lunes a las 2am
  workflow_dispatch:

jobs:
  snyk-container-security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Permite escribir eventos de seguridad
      contents: read         # Permiso para leer el contenido del repositorio
    defaults:
      run:
        working-directory: Backend  # Establece el directorio de trabajo predeterminado
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - name: Construir imagen Docker
        run: docker build -t fastapi-vt:${{ github.sha }} .
      
      - name: Ejecutar Snyk Container Test
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >
            --docker fastapi-vt:${{ github.sha }}
            --severity-threshold=critical
            --sarif-file-output=snyk-container.sarif
            --project-name=cibersecurity-backend-${{ github.ref_name }}
            --monitor
            --exit-code=0
            --exclude-base-image-vulns
            --policy-path=.snyk
      
      - name: Subir archivo SARIF para GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk-container.sarif